# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nodejs sync push sale orders

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      TABLE_ORDERS_NAME:
        description: "Tên bảng Orders"
        required: true
        type: string

      TABLE_ORDER_ITEMS_NAME:
        description: "Tên bảng Order Items"
        required: true
        type: string

      FROM:
        description: "Từ ngày (YYYY/MM/DD)"
        required: true
        type: string

      TO:
        description: "Đến ngày (YYYY/MM/DD)"
        required: true
        type: string

jobs:
  sync-orders-pushS-job:
    runs-on: ubuntu-latest
    environment: sync-push-sale

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run sync-orders-pushS.js
        env:
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          KIOTVIET_RETAILER: ${{ secrets.KIOTVIET_RETAILER }}
          KIOTVIET_RETAILER_OLD: ${{ secrets.KIOTVIET_RETAILER_OLD}}
          KIOT_CLIENT_ID: ${{ secrets.KIOT_CLIENT_ID }}
          KIOT_CLIENT_ID_OLD: ${{ secrets.KIOT_CLIENT_ID_OLD }}
          KIOT_SECRET: ${{ secrets.KIOT_SECRET }}
          KIOT_SECRET_OLD: ${{ secrets.KIOT_SECRET_OLD}}
          PUSH_SALE_CLIENT: ${{ secrets.PUSH_SALE_CLIENT}}
          PUSH_SALE_API_TOKEN: ${{ secrets.PUSH_SALE_API_TOKEN}}
          LARK_APP_ID_PS: ${{ secrets.LARK_APP_ID_PS }}
          LARK_APP_SECRET_PS: ${{ secrets.LARK_APP_SECRET_PS }}
          BASE_ID: ${{ vars.BASE_ID }}
          TABLE_ORDERS_NAME: ${{ inputs.TABLE_ORDERS_NAME || vars.TABLE_ORDERS_NAME }}
          TABLE_ORDER_ITEMS_NAME: ${{ inputs.TABLE_ORDER_ITEMS_NAME || vars.TABLE_ORDER_ITEMS_NAME }}
          FROM: ${{ inputs.FROM || vars.FROM }}
          TO: ${{ inputs.TO || vars.TO }}

        run: node main.js
